server:
  port: 8080
  ssl:
    enabled: true
    key-store: /Users/olevegic/Base/development/study/zopa/soa/ssl/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: soa-services

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  routes:
    heroes-service:
      path: /api/heroes/**
      serviceId: heroes-service
      strip-prefix: false
    human-beings-service:
      path: /api/**
      serviceId: human-beings-service
      strip-prefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true

ribbon:
  eureka:
    enabled: true  # Включаем Eureka для автоматической балансировки
  ConnectTimeout: 10000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
