server:
  port: 8080
  ssl:
    enabled: true
    key-store: C:\Users\alina\IdeaProjects\soa\ssl\keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: soa-services

spring:
  application:
    name: zuul-gateway
  web:
    cors:
      enabled: true
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  routes:
    heroes-service:
      path: /api/heroes/**
      url: http://localhost:8091
      strip-prefix: false
      sensitive-headers:  # Разрешить передачу CORS заголовков
    human-beings-service:
      path: /api/human-beings/**
      url: http://localhost:9090
      strip-prefix: false
      sensitive-headers:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ignored-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers  # Не игнорировать CORS заголовки

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 10000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
