server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: service1-rest-adapter

# SOAP Service URL
soap:
  service:
    url: ${SOAP_SERVICE_URL:http://localhost:8082/service1-soap/HumanBeingService}

logging:
  level:
    itmo.soa.adapter: INFO
